clients: 5
local: 1
debug: 1
deploy_function: 0
function_memory: 256
function_timeout: 120
function_region: "us-central1"
credentials: "/Users/cristianglavan/Work/eroot/hive-mind/credentials.json"
concurrency: 1
number: 100
url: https://google.com
